### PR TITLE
0.5.2 errorhandling

### PR DESCRIPTION
**Pull request by vikasprashar99**
Handled the errors in a seprate file and added common text field with valdiator 
@Rahul-Vijay @Rajat012k please look out for any issues or merge.

### CODE REVIEW

**Comment by Rahul-Vijay** [comment]
Observations - 

- **Registration**  - If you type in some text in both username and email(valid one) and leave mobile field empty, and then click on signup, it goes back to username and email (even though both are filled and valid, no errors) but empty error in mobile.

- **Login** - Looks Good

**Review by Rahul-Vijay — CHANGES_REQUESTED** [review]
See my observations

**Comment by vikasprashar99** [comment]
> Observations -
> 
> * **Registration**  - If you type in some text in both username and email(valid one) and leave mobile field empty, and then click on signup, it goes back to username and email (even though both are filled and valid, no errors) but empty error in mobile.
> * **Login** - Looks Good
in registration i am facing issue in setting the index from the custom text form field file that's why for now i have routed to first index for any errors

**Comment by vikasprashar99** [comment]
I am facing issue in setting the index on register screen from customform field that's why for now i have set index to 0 for any errors in validation

**Comment by vikasprashar99** [comment]
> See my observations

@Rahul-Vijay can you check again , issue fixed

**Review by Rahul-Vijay — APPROVED** [review]
OK ✅

**Pull request merged**
