### PR TITLE
Added authorization to all Cart API requests

### PR DESCRIPTION
**Pull request by vikasprashar99**
used the new postman API's to post and get data from Firestore

### CODE REVIEW

**Comment by vikasprashar99** [comment]
@Rahul-Vijay Can you check once again all crud operations must be working, i am getting a error while running the app

**Comment by vikasprashar99** [comment]
> What about the tokens that are being stored ? Have a look at `storesList.dart` at `_saveDeviceToken()`. We need to make sure even they are send requests to server and not directly to Firestore. Also the same applies in the `Business App Repo`.

i will take a look into it and all crud operations of cart are working?

**Comment by vikasprashar99** [comment]
@Rahul-Vijay @Nsharma96 didn't sent the API for saving the device token, all if them were cart API's.

**Comment by Rahul-Vijay** [comment]
> > What about the tokens that are being stored ? Have a look at `storesList.dart` at `_saveDeviceToken()`. We need to make sure even they are send requests to server and not directly to Firestore. Also the same applies in the `Business App Repo`.
> 
> i will take a look into it and all crud operations of cart are working?

I think update API is not working. Add, delete and get are working

**Comment by Rahul-Vijay** [comment]
> @Rahul-Vijay @Nsharma96 didn't sent the API for saving the device token, all of them were cart API's.

Okay I think @Nsharma96 will write the required APIs

**Comment by vikasprashar99** [comment]
> > > What about the tokens that are being stored ? Have a look at `storesList.dart` at `_saveDeviceToken()`. We need to make sure even they are send requests to server and not directly to Firestore. Also the same applies in the `Business App Repo`.
> > 
> > 
> > i will take a look into it and all crud operations of cart are working?
> 
> I think update API is not working. Add, delete and get are working

is that API working through Postman?

**Comment by Nsharma96** [comment]
> 
> 
> > > > What about the tokens that are being stored ? Have a look at `storesList.dart` at `_saveDeviceToken()`. We need to make sure even they are send requests to server and not directly to Firestore. Also the same applies in the `Business App Repo`.
> > > 
> > > 
> > > i will take a look into it and all crud operations of cart are working?
> > 
> > 
> > I think update API is not working. Add, delete and get are working
> 
> is that API working through Postman? because it looks fine on frontend

All APIs were tested and are working. For Update API to work make sure the collection and doc you are trying to update already exists on firestore and make sure its a update request not post else it will throw an error. You can attach the request code here if you still face issue.

**Comment by vikasprashar99** [comment]
`   StorageSharedPrefs p = new StorageSharedPrefs();
    String id = await p.getId();
    String token = await p.getToken();
    String url = APIService.updatecartAPI;
    Map<String, String> requestHeaders = {'x-auth-token': token};

    String body = jsonEncode({
      'userPrice': newp,
      'userQuantity': newq,
      'uniqueId': docId,
      'userId': id
    });
    var response = await http.put(url, body: body, headers: requestHeaders);
    if (response.statusCode == 200) {
      print("success");
    } else {
      throw Exception('something is wrong');
    }`

@Nsharma96 Please check if the request is fine

**Comment by Nsharma96** [comment]
> 
> 
> `StorageSharedPrefs p = new StorageSharedPrefs();
> String id = await p.getId();
> String token = await p.getToken();
> String url = APIService.updatecartAPI;
> Map<String, String> requestHeaders = {'x-auth-token': token};
> 
> ```
> String body = jsonEncode({
>   'userPrice': newp,
>   'userQuantity': newq,
>   'uniqueId': docId,
>   'userId': id
> });
> var response = await http.put(url, body: body, headers: requestHeaders);
> if (response.statusCode == 200) {
>   print("success");
> } else {
>   throw Exception('something is wrong');
> }`
> ```
> 
> @Nsharma96 Please check if the request is fine

There are no cart entries in firestore update wont work.

**Comment by vikasprashar99** [comment]
> > `StorageSharedPrefs p = new StorageSharedPrefs();
> > String id = await p.getId();
> > String token = await p.getToken();
> > String url = APIService.updatecartAPI;
> > Map<String, String> requestHeaders = {'x-auth-token': token};
> > ```
> > String body = jsonEncode({
> >   'userPrice': newp,
> >   'userQuantity': newq,
> >   'uniqueId': docId,
> >   'userId': id
> > });
> > var response = await http.put(url, body: body, headers: requestHeaders);
> > if (response.statusCode == 200) {
> >   print("success");
> > } else {
> >   throw Exception('something is wrong');
> > }`
> > ```
> > 
> > 
> > @Nsharma96 Please check if the request is fine
> 
> There are no cart entries in firestore update wont work. again:
> 
> * Make sure cart entries you are trying to update exists in firestore.

Alright

**Pull request merged**
