### PR TITLE
0.5.2 pullrefresh

### PR DESCRIPTION
**Pull request by vikasprashar99**
Features in PR

- Pull to refresh feature on Main Screen as well as the Products Screen.

- Separate file for Appbar so that it would remain sticky

### CODE REVIEW

**Review by Rajat012k — CHANGES_REQUESTED** [review]
@vikasprashar99 pls drop a PR when it is complete there is only one screen with pull to refresh feature.

**Comment by vikasprashar99** [comment]
> @vikasprashar99 pls drop a PR when it is complete there is only one screen with pull to refresh feature.

all complete bro

**Comment by Rajat012k** [comment]
> > @vikasprashar99 pls drop a PR when it is complete there is only one screen with pull to refresh feature.
> 
> all complete bro

only main screen completed pls implement this in full app

**Comment by vikasprashar99** [comment]
> > > @vikasprashar99 pls drop a PR when it is complete there is only one screen with pull to refresh feature.
> > 
> > 
> > all complete bro
> 
> only main screen completed pls implement this in full app

products screen is also completed

**Comment by Rajat012k** [comment]
> > > > @vikasprashar99 pls drop a PR when it is complete there is only one screen with pull to refresh feature.
> > > 
> > > 
> > > all complete bro
> > 
> > 
> > only main screen completed pls implement this in full app
> 
> products screen is also completed

i said all screens not 1 and 2

**Comment by Rahul-Vijay** [comment]
any updates ? @vikasprashar99 @Rajat012k

**Comment by vikasprashar99** [comment]
> any updates ? @vikasprashar99 @Rajat012k 

Do we require this in my orders section?

**Review by Rahul-Vijay — APPROVED** [review]
✅

**Pull request merged**
