### PR TITLE
Customised Internet Error Message

### PR DESCRIPTION
**Pull request by Rajat012k**
mainlanding page connectivity issue solved waiting for the UI that needs to be implemented.

### CODE REVIEW

**Review by vikasprashar99 — CHANGES_REQUESTED** [review]
Internet Lost Error message not customized

**Comment by Rajat012k** [comment]
> Internet Lost Error message not customized

Internet Lost as in?

**Comment by Rahul-Vijay** [comment]
updates ? @vikasprashar99 @Rajat012k

**Comment by vikasprashar99** [comment]
> updates ? @vikasprashar99 @Rajat012k

It's completed and ready to be merged

**Review by Rahul-Vijay — APPROVED** [review]
✅

**Pull request merged**
