### PR TITLE
0.5.2 cd

### PR DESCRIPTION
**Pull request by Rahul-Vijay**
- CD for beta builds

### CODE REVIEW

**Comment by vikasprashar99** [comment]
what needs to be done in this?

**Comment by Rahul-Vijay** [comment]
@vikasprashar99 @Rajat012k  configure your machines for using this CD as from version **0.5.4** you will be releasing all Beta / Early access builds to play store. We can add 2 more sub-versions **0.5.2+3** & **0.5.2+4** to solve any more issues / bugs, optimise code etc which I will release manually. 
We only release Production version manually rest should be automated.

**Comment by vikasprashar99** [comment]
> @vikasprashar99 @Rajat012k configure your machines for using this CD as from version **0.5.4** you will be releasing all Beta / Early access builds to play store. We can add 2 more sub-versions **0.5.2+3** & **0.5.2+4** to solve any more issues / bugs, optimise code etc which I will release manually.
> We only release Production version manually rest should be automated.

on it

**Comment by Rajat012k** [comment]
@vikasprashar99 is this sorted?

**Comment by vikasprashar99** [comment]
> @vikasprashar99 is this sorted?

need the key

**Comment by Rajat012k** [comment]
@Rahul-Vijay pls sort @vikasprashar99 issue

**Comment by vikasprashar99** [comment]
@Rajat012k Please read the Fastlane docs again maybe I am missing something

**Pull request closed without merging**
