### PR TITLE
0.5.2 bugs

### LINKED ISSUE #90: [Bug] Addition & Subtraction of Quantities
Steps to Reproduce:

- Click on any product, add some quantity
- Close the product details page
- Go to some other page and come back 
- Click on the same product and try to add or subtract quantity 

Expected Behaviour:

- Addition or subtraction instantly 

Current Behaviour:

- Only after clicking on (-) multiple times, only then it is editable 

Fix priority: **HIGH**

### PR DESCRIPTION
**Pull request by Rahul-Vijay**
- Fixes the quantity Bug
- Add Hive for shopping cart
- closes #90

### CODE REVIEW

**Comment by Rahul-Vijay** [comment]
- check for any more bugs or issues and merge the PR if there are none @vikasprashar99

**Comment by vikasprashar99** [comment]
on closing the app and re-opening the cart items are gone

**Review by vikasprashar99 — COMMENTED** [review]
after adding items from bestsellers not able to add items in categories section

**Comment by Rahul-Vijay** [comment]
> on closing the app and re-opening the cart items are gone

we still have some issues that we need to figure out before we implement this.

**Comment by Rahul-Vijay** [comment]
> after adding items from bestsellers not able to add items in categories section

new commit, check again

**Comment by vikasprashar99** [comment]
Everything works fine!

**Review by vikasprashar99 — APPROVED** [review]
Everything works fine! I think for now this PR can be merged

**Pull request merged**
