### PR TITLE
[0.5.2+3] beta version

### PR DESCRIPTION
**Pull request by vikasprashar99**
All widget tests are passing.

@Rahul-Vijay Please review and merge.

### CODE REVIEW

**Comment by Rahul-Vijay** [comment]
We'll hold this PR for next release in the coming 2 days

**Comment by Rajat012k** [comment]
@Rahul-Vijay @vikasprashar99  reopening this PR as the bug sorted in this branch. PLease review

**Review by Rahul-Vijay — CHANGES_REQUESTED** [review]
remove unnecessary prints

**Comment by Rajat012k** [comment]
@Rahul-Vijay ok I will I thought I have already removed all

**Comment by Rahul-Vijay** [comment]
> @Rahul-Vijay ok I will I thought I have already removed all

@Rajat012k no commits yet ?

**Comment by vikasprashar99** [comment]
> > @Rahul-Vijay ok I will I thought I have already removed all
> 
> @Rajat012k no commits yet ?

removed Prints

**Pull request merged**
